### ISSUE TITLE
Bitfinex.com pairs/ tickers, please update

### ISSUE THREAD

**Issue by Sprkz** [aneonex/BitcoinChecker#10]
hi guys,  - mark.stevenson@bitfinex.com
https://docs.google.com/spreadsheets/d/18TagCpffpKRco_sXbIc6MrMtTN0h7x87zqlZDDl8Waw/edit?usp=sharing

I see there are some pairs for Bitfinex are not yet included on Bitcoin Checker. you have some recent pairs, but no 4 character tickers:  eg.  $LINK, $BAND etc.

the above share doc. inlcudes current updated tickets - endpoints including our Derivatives tickers.
Any doubts, just drop me a mail.
thanks guys, great app.

**Comment by aabiryukov** [comment]
The update will be included in the next app version (2.11)
Thank you for feedback.

**Comment by Sprkz** [comment]
Amazing. thank you. I'll msg you guys here each month with the latest updates.
Great work, great app!
