### ISSUE TITLE
Do Not Disturb Exceptions

### ISSUE THREAD

**Issue by sevendaryl** [aneonex/BitcoinChecker#102]
Currently the notification sound is still activated if there is any entry in "Calls, messages and conversations" section. Screenshot as attached.

Is it possible to not bypass the DND settings?

Tested on Samsung Galaxy Note 8, 9 and 20.

![Screenshot_20210406-015241_Settings](https://user-images.githubusercontent.com/56883229/113606869-24f34a80-967b-11eb-8c34-a896c6ebe3c4.jpg)

**Comment by aneonex** [comment]
It is customizable in the app. See app settings: Customize Sounds -> Advanced: "Choose audio stream for Alarm sound".
By default the app using "Alarm stream" for sound that ignores DnD mode as well as other Android alarms. You can change the audio stream to "Ring and Notification stream" so as not to bypass the DnD mode.

**Comment by sevendaryl** [comment]
I've selected "Ringtone and Notification stream" but it will still sound whenever I have either of the following settings under DND:

- Calls, messages and conversations
- Alarms and sounds >

**Comment by aneonex** [comment]
I researched the issue. 
There are different behaviors in Android 10 and 11. I was able to reproduce on Android 10.

In the next app version (v2.31) it will be be fixed for all android versions and regardless of the selected alarm stream.
I'll let you know when the app is published (in the coming days).

**Comment by sevendaryl** [comment]
Thanks a lot for finding out the problem and look forward to the updated app.

And of course thousand thanks for taking over the project from the original developer!

**Comment by aneonex** [comment]
The update published to Google Play. See app v2.32.

**Comment by aneonex** [comment]
Some changes in the latest version (v2.33). 

The choice of audio stream in the app settings will affect the behavior in DnD mode:
- when "Ring and Notification stream" is selected, the app will not bypass DnD mode. This audio stream is set by default.
- when "Alarm stream" is selected, the app will bypass DnD mode.
