### ISSUE TITLE
Please add support for led cover (Feature request)

### ISSUE THREAD

**Issue by lbalan791** [aneonex/BitcoinChecker#103]
As title says support for Led Cover would be desired. I used this application for the longest time but support for this type of notifications makes it hard to be notified on price updates.

Here is a link: https://www.samsung.com/us/mobile/mobile-accessories/phones/galaxy-s10-led-wallet-cover-black-ef-ng973pbegus/

**Comment by aneonex** [comment]
I don't know how this feature can be implemented. This is a very specific technology from Samsung and does not have a public API.
Can you give an example of which apps support this feature, while not created by Samsung?

**Comment by aneonex** [comment]
Cannot be implemented
