### ISSUE TITLE
Add note input box

### ISSUE THREAD

**Issue by PackPro21** [aneonex/BitcoinChecker#105]
Is it possible to add a note to each pair selected?

For example, under the alarms display section add a text box that you can add notes like 'buy at $X' or 'Check trend'......

The box only needs to be a single line.

Thank you.

**Comment by brianlaudi** [comment]
This would be awesome, even been waiting for this feature! are there any plans to get implement shouldn't be difficult to include a note to alarms. Thank you all!

**Comment by aneonex** [comment]
Good news!
Notes feature is implemented and will be available in the next app release v2.59 (near 1-2 week).

## Design preview

### Checker editor
![image](https://user-images.githubusercontent.com/69394046/184517186-51fd6b50-92ec-4678-8ac2-7ea1292bc82f.png)

### Notes editor
![image](https://user-images.githubusercontent.com/69394046/184517130-130d3d85-7b39-4dfa-a407-7ae9d6d0c765.png)

**Comment by aneonex** [comment]
Also the notes will be displayed in the main list:

![image](https://user-images.githubusercontent.com/69394046/184532634-78bcdbe0-8321-4472-9f10-15791c819bd7.png)

**Comment by aneonex** [comment]
Release v2.59 with the note feature is available in Google Play.
