### ISSUE TITLE
Option to disable analytics/crashlytics

### ISSUE THREAD

**Issue by razordynamics** [aneonex/BitcoinChecker#111]
Can we have an option/toggle to disable analytics & crashlytics reporting? The app periodically "dials home" to firebase-settings.crashlytics.com. For the sake of privacy, can we have an option to disable this?

**Comment by aneonex** [comment]
The app uses the standard Google Firebase tools to collect **anonymized** information about issues inside the app (errors, performance, hangs, general device characteristics) and basic analytics. 
More info about Crashlytics: https://firebase.google.com/docs/crashlytics

This information **helps a lot in developing the application for free**.

If additional paid features become available in the app in the future, this will include the option to disable telemetry. There are no such plans in the near future.
