### ISSUE TITLE
PLEASE ADD XAUUSD(GOLDUSD) PAIR 

### ISSUE THREAD

**Issue by mslint01** [aneonex/BitcoinChecker#114]
Hi please can anyone put Goldusd pair in this? I am willing to pay just for this modded app that can alert me of gold prices

**Comment by terrorist96** [comment]
You could add Bitfinex's XAUT/USD pair. Or Binance's PAXG/USDT pair.

**Comment by mslint01** [comment]
They have different  live price :( pleaseee help me up sirrrrr

**Comment by terrorist96** [comment]
That's the nature of watching a price of a currency pair on a particular exchange. There will always be small variations. There's no other option.

**Comment by mslint01** [comment]
Can you check sir if we can add live price of gold from oanda?

**Comment by terrorist96** [comment]
This app is for cryptocurrencies only. @aneonex please close this.

**Comment by aneonex** [comment]
I agree with @terrorist96, and thanks for the clarifications.
