### ISSUE TITLE
Price on Binance Future is wrong on Oneplus 9R

### ISSUE THREAD

**Issue by tungns1210** [aneonex/BitcoinChecker#116]
Other phone is ok but my phone price did not right. I use Oneplus 9R on Oxygen OS 11.2.1.2.LE28DA

**Comment by aneonex** [comment]
Please describe the problem in more detail.

**Comment by tungns1210** [comment]
Price is lagging or something, it doesnt show the right number. But it works fine on my Oneplus 5T, so maybe my Oneplus 9R cause that problem. All the Binance Future pairs has that problem.

**Comment by aneonex** [comment]
I guess this is an Oxygen OS specific problem.
1) What is the price update interval you have set?
2) Is the problem also exists with other exchanges (eg Bitfinex), or just Binance Futures?

**Comment by tungns1210** [comment]
1.  Its 15 seconds
2. Just Binance Future, even Binance Spot is fine.
Thanks a lot, you are the man, and this app is the best, I dont use iPhone because it doesnt have this.

**Comment by aneonex** [comment]
Please give me a real example:
- Problem pair
- What price is displayed in the application
- What is the price in reality on Binance Futures

This can help localize the problem.

P.S.
Glad to hear a good review, it's always encouraging :)

**Comment by aneonex** [comment]
I found issue with pairs ETH-USDT, BTC-USDT.
Instead of perpetual futures, were used random periodic futures recently added on Binance.

The fix will be included in the next app release v2.38

**Comment by aneonex** [comment]
The app published on Google play.
