### ISSUE TITLE
Add new excahnge: coinswitch kuber

### ISSUE THREAD

**Issue by ProgrammingPlanet** [aneonex/BitcoinChecker#118]
Please add the coinswitch kuber excahnge rates.

You can find api url on https://coinswitch.co/

Goto dev tools and network tab, where you find a request named "coins"

That's the api url.....

**Comment by aneonex** [comment]
I could not find an official public API for Coinswitch kuber.
Their web site (analized via DevTools) uses this link: https://coinswitch.co/proxy/in/api/v1/coins - but it contains too big size (all tokents and prices), and it is not official (may be changed at any time).

Using this link will result in huge traffic. For example if check every minute it is more than 2GB for month for every pair. This is not acceptable for the Bitcoin Checker.
