### ISSUE TITLE
Text to speech error

### ISSUE THREAD

**Issue by Simon568** [aneonex/BitcoinChecker#119]
Uniswap v2 HEX USD pair reads incorrectly leaving out the first whole number after comma
Rexample 0,0866 reads 0,066

**Comment by aneonex** [comment]
I am unable to reproduce the problem.
Is there a problem with other values, for example 0.09xxx, or with other exchanges?
It is possible that the "0" [ou] and "8" [eight] sound similar on a speech synthesizer, which causes confusion. The app uses standard Android system Text-to-Speech engine.

**Comment by aneonex** [comment]
Outdated
