### ISSUE TITLE
Show Last update time on the widget. 

### ISSUE THREAD

**Issue by Transisto** [aneonex/BitcoinChecker#129]
The widget is not self updating most of the time.

The only way I know if it work is to refresh and see the number changes.

**Comment by aneonex** [comment]
Provide more info please:
1) Is the problem still exists in the latest app version 2.40?
2) What device are you using (model, android version)
3) What price update interval have you set?
4) Try to reboot your device. Is a problem still remains?

**Comment by Transisto** [comment]
This is mostly a feature suggestion, If all the ticker update at once, the last updated time could be written somewhere, like at top or bottom. or maybe a countdown to next update.

**Comment by aneonex** [comment]
1) In the app, each currency pair is updated separately with according to its own schedule. There is no single time.
2) On the right side, for each pair, the time of the last price from the exchange is displayed. Most often, it corresponds to the real time of the update (depending on the activity of trading on the exchange).

It is not possible to display single common time of the next price update.
If you have an issue with the frequency of price updates, try turn off battery optimization in the app settings.

**Comment by Transisto** [comment]
I must admit the background updates have been much reliable lately. Didn't
touch any setting related to battery.

I think extending the size of the widget could show the time it was last
updated like it does when looking inside the app.
