### ISSUE TITLE
Add Bitpanda Exchange

### ISSUE THREAD

**Issue by Tierchen83** [aneonex/BitcoinChecker#16]
Hello community,

I really like your app and it's extremely useful.

Would it be possible to add the Bitpanda Exchange (https://exchange.bitpanda.com)?

Thanks
Karsten

**Comment by aneonex** [comment]
Bitpanda added and will be included in the next app release.
Thanks for the feedback.

**Comment by Tierchen83** [comment]
Thanks a lot :)
