### ISSUE TITLE
Unable to sync pairs with BKEX

### ISSUE THREAD

**Issue by JC-S** [aneonex/BitcoinChecker#163]
Showing error message: "Error: Network error (Connect)"

**Comment by JC-S** [comment]
App version: 2.49.2 from Google play store.

**Comment by aneonex** [comment]
Fixed. Will be included in the next app version 2.49.3.

**Comment by JC-S** [comment]
Wow, new update just rolled out on Play store. This issue was solved so timely I can't even believe it!
Thank you for your great work! Keep it up!
