### ISSUE TITLE
Widget to Main app problem

### ISSUE THREAD

**Issue by Wolftech-Chile** [aneonex/BitcoinChecker#165]
Hello, when I click on the widget, it no longer takes me to the application

**Comment by aneonex** [comment]
I can't reproduce the issue. 
Please, provide more details:
1) Version of the Bitcoin Checker.
1) Your phone model and version of Android.
1) Do you have this issue always reproduced or only sometimes?
1) Where on the widget do you click?
1) How do you try to get into the application when an issue occurs? Does launching through the application icon work?
1) Maybe some other details or patterns?

**Comment by Wolftech-Chile** [comment]
Hello, thank you, I answer you point by point:

1. 2.49.3
2. Xiaomi Redmi Note 10s, MIUI Global 12.5.14, Android 11RP1A 200720.011
3. Always happens
4. Anywhere
5. I put an app icon near the widget
6. Link to video https://twitter.com/i/status/1467926040114778117 
The launcher that i use is: Mi Launcher 1.1.2 https://mi-app-mi-launcher.es.aptoide.com/app
Thanks!

**Comment by aneonex** [comment]
Thank you for details.

In the video (6.), you click on the widget many times. 
1) What happens if you click on the widget only once and than to the widget's toolbar to open the app?
2) Does the app open when you click the standard app icon instead on the widget?

I tried to reproduce on Xiaomi Note 7 (default launcher) / Android 10, Google Pixel / Android 12, the app opens successfully after many clicks.
This seems to be an issue with the old MI Launcher 1.1.2 (latest update on 06-03-2019).

**Comment by Wolftech-Chile** [comment]
Hi
1. Nothing happens
2. It is opened by clicking on the standard app icon 

Yes, that's why I mentioned the launcher, I think I'll have to change it :(
I left you a pull request that I couldn't enter in the corresponding section, thanks friend and make a licenced version with more feaures, like charts, add tokens, etc
Thanks!

**Comment by Wolftech-Chile** [comment]
Hello, it does not work with nova launcher or lynx launcher either, of all
the attempts (which were many during 20 minutes) it only worked once and it
took me to the program by clicking on the top bar of the widget, this is
what I did:

I went to linx launcher where it does not work, I went back to nova
launcher and it worked only that time

Muchas Gracias

Atentamente
Gustavo Meneses U
Ingeniero en Informática

Mensaje enviado desde móvil

**Comment by aneonex** [comment]
I tested the app on emulator with Android 11 with Nova launcher and Lynx launcher (latest versions from Google Play). 
The app always opens when clicking on the widget top bar. Can't reproduce your issue.

Maybe you need to update android system apps from Google Play?

**Comment by Wolftech-Chile** [comment]
I have discovered that if I use the app icon and then click on the widget
if it works, it can be seen in the video.
My phone is updated in every way
The video > https://twitter.com/i/status/1468987787487727621
Muchas Gracias

Atentamente
Gustavo Meneses U
Ingeniero en Informática

**Comment by aneonex** [comment]
Unfortunately, there is nothing more help with this issue. Perhaps a problem in a specific environment.
