### ISSUE TITLE
Widget display problems in the Hebrew language (phone language)

### ISSUE THREAD

**Issue by saaginoy** [aneonex/BitcoinChecker#166]
When the main language of the phone is Hebrew, the widget shows partial information
![IMG_20211209_090208](https://user-images.githubusercontent.com/16302915/145349467-1e34036a-0d63-4ed1-8e2a-a356b56a046d.jpg)

**Comment by aneonex** [comment]
Great, thank you! :)
I fixed this issue. The fix will be included in the next app release v2.50.

For RTL languages the widget will look like this:

![image](https://user-images.githubusercontent.com/69394046/145471857-3413d651-71c8-4bfa-b271-555dc902d918.png)

Let me know if you have additional comments.

**Comment by saaginoy** [comment]
Great, thanks!!!!
I've been using a launcher for two years, just because of that...
Do you have an estimate of when it's going to be released? Can't wait :-)
I've been using the app since about 2014

**Comment by aneonex** [comment]
The release will be in about 2 weeks.

**Comment by aneonex** [comment]
The app published to Google Play (v2.50).
