### ISSUE TITLE
[Feature Request] Decimal place options

### ISSUE THREAD

**Issue by Griffaye** [aneonex/BitcoinChecker#172]
I noticed the app defaults to round up to two decimal places on certain coins. Say a coin's value is 3.2256, the app and notification will show 3.23. I would much rather prefer to see 4 decimal places. Might this be implemented as a decimal place option within each notification's currency pair settings? A small-yet-huge quality-of-life improvement.

**Comment by aneonex** [comment]
The app rounds differently for display, depending on the size of the number. E.g.: 123456.123->123456, 0.000012345 -> 0.00001235. 
I agree that three significant digits for your case (3.23) are too little. This will be improved without additional options.

**Comment by aneonex** [comment]
Fixed formatting values between 1 and 10, as for all other smaller values. All values consist of at least 4 significant digits (not only decimals).

The fix will be included to the next app release v2.51.

Example:
Before: 1.12345 -> 1.12, after fix: 1.12345 -> 1.123.

For the rest of the values, nothing has changed. Example:
0.12345 -> 0.1235 (the last digit is rounded)
0.012345 -> 0.01235
0.0012345 -> 0.001235
. . .

This formatting only affects display info. Alarm rules use original full values.
In my opinion, additional option will be superfluous, it will complicate the application.
