### ISSUE TITLE
Global update timeout on Android 11

### ISSUE THREAD

**Issue by Griffaye** [aneonex/BitcoinChecker#173]
Version: 2.50.1
Samsung Galaxy S10, Android 11

I've noticed on Android 11 the app running in the background will timeout sometime in the middle of the night and break. When I wake up from sleeping, I will then have to force stop the app and restart it for it to continue updating the push notifications automatically. This is even with the phone's sleep and power settings disabled, and the app set to 'locked and keep running in the background'. This might be more of a phone timeout issue rather than the app. All I know is that it breaks the app from continuing to ping updates.

**Comment by aneonex** [comment]
What price update interval are you using?

**Comment by Griffaye** [comment]
I ended up switching the price update interval to 30 seconds and it seems to have fixed the issue. I originally had it set really low at 5-10 seconds. I think that was bricking the app to push further updates. Also, now that Android has updated to Android 12, I've noticed more consistency with the notifications as well. It also makes them look nicer :)
