### ISSUE TITLE
Translate (pt-br)

### ISSUE THREAD

**Issue by pindarogb** [aneonex/BitcoinChecker#174]
How I help translate to pt-br?

**Comment by aneonex** [comment]
I added localized app resources into "translate" folder: https://github.com/aneonex/BitcoinChecker/tree/master/translate
See the Readme file there with a quick translation guide.
Thank you for the help!

**Comment by pindarogb** [comment]
I'm sending a folder with files translated.

**Comment by aneonex** [comment]
Please send again to aneonex.software@gmail.com. The Readme file contained a typo in the e-mail (now fixed).

**Comment by pindarogb** [comment]
I created a pull request to add files.

**Comment by aneonex** [comment]
Portuguese (Brazil) (pt-BR) localization will be added in the next app release v2.51.
@pindarogb thanks for the translation!

Also in the new version of the app, the ability to switch between languages is implemented. This will be available in the settings window. Available three languages: English, Italian, Portuguese (Brazil).
