### ISSUE TITLE
Widget can not be added with Go Launcher

### ISSUE THREAD

**Issue by OrhanCinar** [aneonex/BitcoinChecker#177]
I have this problem for a couple of months, i don't know what causes the problem. 
When a add the widget to the screen i get this error "Unable to access the application, try to restart GO Launcher" and it cancels the operation. This is just happening with GO Launcher.  I have 2 different phones and i get the same error.

Is there a way to fix this
![photo_2022-01-04_15-23-41](https://user-images.githubusercontent.com/322158/148073445-bb1d3df1-7382-4ec6-afee-4c104b59f23e.jpg)
?

**Comment by aneonex** [comment]
The issue was found and resolved in the test environment. This will be fixed in the next app release v2.51 (in about a week).
Thanks for reporting the issue.

**Comment by aneonex** [comment]
Updated app version 2.51 is available in Google Play. Is your issue solved?

**Comment by OrhanCinar** [comment]
Yes, problem solved, thanks.
