### ISSUE TITLE
Switch off notifications completely?

### ISSUE THREAD

**Issue by georgjaehnig** [aneonex/BitcoinChecker#189]
Hi, I want to use only the widget, no notifications. In the Settings, I've switched off everything related to notifications. Still, I'm seeing them. How can I turn this off?

![Screenshot_2022-02-03-12-42-49-454_com brave browser](https://user-images.githubusercontent.com/1092628/152337440-51618089-fb68-40b9-a37d-b65459b36c00.jpg)

**Comment by aneonex** [comment]
You can turn off all Bitcoin Checker notifications through the standard android functionality: https://support.google.com/android/answer/9079661
