### ISSUE TITLE
Group notification icon color option

### ISSUE THREAD

**Issue by Griffaye** [aneonex/BitcoinChecker#191]
May you please add an option to set the group notification icon color to white? The tiny red icon is slightly unpleasing to look at while every other tiny icon is always white. Just my two cents. Thank you for your time!

**Comment by aneonex** [comment]
On different devices and versions of android, the icon may be different. 
Can you provide screenshot and phone model?

**Comment by Griffaye** [comment]
> On different devices and versions of android, the icon may be different. Can you provide screenshot and phone model?

Yes, here you are

![Screenshot_20220209-202508](https://user-images.githubusercontent.com/96925400/153319338-efb922df-a2e5-4b44-a734-a688a3a14118.jpg)

**Comment by aneonex** [comment]
Fixed in the latest app release v2.53.1 (rollout started). This icon is now white.
