### ISSUE TITLE
Sync of bitbay.net exchange "Error: Network error (UnknownHost)"

### ISSUE THREAD

**Issue by AlbertusPl2020** [aneonex/BitcoinChecker#194]
Dear Bitcoin Checker Team,

Please note that the Sync of bitbay.net exchange has Error: Network error (UnknownHost). I use bitcoin checker every day. Can you fix this issue?

Note:
The bitbay.net has been rebranded to zonda.

Thank you in advance.

Best regards,
User of bitcoin checker

**Comment by aneonex** [comment]
The fix will be included in the next app release v2.52 (near two weeks)

What is changed:
1) "BitBay" renamed to "Zonda (BitBay)"
2) Using the new Zonda API
