### ISSUE TITLE
different types of alarms

### ISSUE THREAD

**Issue by tarantula3535** [aneonex/BitcoinChecker#196]
future request 
Can an indicator-based alarm be set? just like tradinqview's
e.g. 
if price crossover ema200 
if BB%b value crossundre 1

**Comment by mert-donmez** [comment]
> 

hocam konudan bağımsız fakat bir sorum olacaktı.
freqtrade repisotory kısmında MOST indikatörünüzü gördüm indikatör kısmında `df[mavalue]=ta.EMA(df , timeperiod=length)`  lenght yerine 1 verince hata veriyor sebebini biliyor musunuz ?

**Comment by mert-donmez** [comment]
> future request Can an indicator-based alarm be set? just like tradinqview's e.g. if price crossover ema200 if BB%b value crossundre 1

hocam konudan bağımsız fakat bir sorum olacaktı.
freqtrade repository kısmında MOST indikatörünüzü gördüm indikatör kısmında` df[mavalue]=ta.EMA(df , timeperiod=length)` lenght yerine 1 verince `Exception: TA_EMA function failed with error code 2: Bad Parameter (TA_BAD_PARAM)` hatası veriyor sebebini biliyor musunuz ?

**Comment by aneonex** [comment]
Good idea, but exchanges do not provide these indicators, so a middleware infrastructure is required. Currently, the app receives all data **directly** from the selected exchange.
Perhaps this feature will appear in the future as a paid option (not in the near future).
