### ISSUE TITLE
Syncing Binance

### ISSUE THREAD

**Issue by MomoJumbo** [aneonex/BitcoinChecker#201]
Hi there
It seems you did good work here.
But I have  a problem.
I couldn't sync pairs for any exchange in the app.
Any solution for that?
Thanks any way.

**Comment by aneonex** [comment]
Check your internet access to Binance. Open in browser on phone Binance api url: https://api.binance.com/api/v3/exchangeInfo
If Binance api accessable, take a screenshot of the error, please.

**Comment by MomoJumbo** [comment]
Tried to open api url but it opened a white page with a long code line in it that I couldn't even copy that.
I took screenshot of start of code line.
![IMG_20220412_171056](https://user-images.githubusercontent.com/37087932/162964712-dadb0f90-1fb5-47de-8eb0-11ae9491a335.jpg)

**Comment by aneonex** [comment]
What error are you getting in the Bitcoin checker when sync pairs? Can you provide a screenshot with error?

**Comment by MomoJumbo** [comment]
![IMG_20220413_003502](https://user-images.githubusercontent.com/37087932/163044607-3f8cc5c6-1769-4a57-9490-8a20067169a9.jpg)

**Comment by aneonex** [comment]
There are different reasons (If this problem with all exchanges):
1) You have too slow internet connection.
2) Android is blocking internet connection for the app. Check app permissions in Android settings. Or you have some kind of software installed that blocks the Internet. Or the manufacturer of your Android device sets additional restrictions.
