### ISSUE TITLE
Alarm has sound but notification is not showing

### ISSUE THREAD

**Issue by jackychio4585** [aneonex/BitcoinChecker#203]
First of all, thank you so much for helping this project to keep going after a long period of dropped out from original developers! 

I had been trying out different short period percentage change alarm like 30sec to 1min with many pairs of course. sometimes it will show notification but sometimes i can hear it but dont see it updated. Am i using it in the wrong way or should I be limited the number of pairs? currently at about 100 pairs on binance.

Thank you.

by the way you definitely have to charge to like a one time fee or low monthly fee. it is a great app.

**Comment by aneonex** [comment]
You are using the application correctly, but 100 pairs is quite a lot, I have not tested the application on such volumes, but it should work.

Perhaps you have notifications too often, and then either the system blocks show new notifications (Android has a limit ~25-50 on the maximum number of notifications displayed at one time), or old notifications are replaced by newer ones.
If you notice any pattern in the issue, let me know.

Thank you for the great feedback.
