### ISSUE TITLE
Use ringtone sound instead of media

### ISSUE THREAD

**Issue by bhappyz** [aneonex/BitcoinChecker#21]
Hi,

First thanks for bringing this project back to life. 

Can we get one feature from old version allowing notification sound to follow ringtone level instead of media. This is better in two ways first it doesn't get silenced by media level or being two loud

Second it will allow for notification to show on smart watch
Thanks

**Comment by aneonex** [comment]
Thanks for the feedback.
I will back ringtone level in next releases (not done yet).
But not sure about smart watch, no way to test.

**Comment by aneonex** [comment]
Resolved in the latest app version v2.19 and now available in Google Play.
Added audio strem settings for alarm notifications. Ring/Notification stream by default. See Settings->Customize sounds->Advanced.
