### ISSUE TITLE
Notification for smartwatch

### ISSUE THREAD

**Issue by kuttylakku** [aneonex/BitcoinChecker#210]
It would have been useful to have a live notification or push notification to the smartwatch. Create an app that can be installed on the watch on ios wereos? Must watch live on watch.
Then it would be of great benefit.
Would you please make an app for honor watch ?

**Comment by aneonex** [comment]
Unfortunately, this is difficult to implement (few resources and not enough expertise in smartwatches). Definitely not in the near future.
