### ISSUE TITLE
Feature request: Different notification LED color for price move up and price move down

### ISSUE THREAD

**Issue by bobanm** [aneonex/BitcoinChecker#216]
All notifications show up in green color on my phone LED. Since I keep my phone on vibration only most of the time, I can't distinguish if the notification was triggered by a move up or a move down, without unlocking the phone and checking the notification.

It would be great if a move up would keep showing green notification light, while a move down would show red notification light.

I recall clearly that this is how the original Bitcoin Checker from Mobnetic displays notification colors.

**Comment by aneonex** [comment]
This is a great feature, but unfortunately it can't be implemented. Google has changed the requirements for notifications in the latest versions of Android, and there is no way to flexibly control the LED color for each individual alert.

P.S.
There are some options to do this, but it will negatively affect users without LED indicators. Android does not provide the API to determine the presence of an LED indicator on the device.
