### ISSUE TITLE
Alarm stream sound with DND activated

### ISSUE THREAD

**Issue by JayKay-Gitz** [aneonex/BitcoinChecker#218]
Alarms no longer make a sound when running through alarm stream and Do Not Disturb is activated on the phone.

- Works when DND not activated.
- Alarms set to ignore DND in phone settings, other alarms make noise with DND on.
- Was working fine before, not sure which update broke it for me, been a few weeks since I've had an alarm trigger.

**Comment by aneonex** [comment]
Thanks for the clear description. I will investigate the issue.

**Comment by aneonex** [comment]
I found cause of the issue. It appeared since the latest version v2.58.
In the next release v2.59 this issue will be fixed (~2 week).

**Comment by JayKay-Gitz** [comment]
Can confirm v2.59 has resolved this issue for me.
