### ISSUE TITLE
Network error for Binance

### ISSUE THREAD

**Issue by vincentquest** [aneonex/BitcoinChecker#224]
Binance won't update!
![Screenshot_20221202_081418_Bitcoin Checker](https://user-images.githubusercontent.com/30918364/205301881-52977fa8-f23a-4953-aef8-3e5b7bda12b4.jpg)

**Comment by aneonex** [comment]
This error is response from Binance. Code 451 means "Unavailable For Legal Reasons"
Try to directly open on your device browser Binance API url: https://api.binance.com/api/v3/exchangeInfo
What are you see?

**Comment by aneonex** [comment]
This is possible from the US. In this case, select the "Binance.US" exchange instead of "Binance".
