### ISSUE TITLE
Bybit spot/derivatives revert

### ISSUE THREAD

**Issue by troky** [aneonex/BitcoinChecker#226]
You recently updated Bybit API to v3 (spot) while v2 (derivatives) still works.
Thing is that derivatives exchange is used much more than spot (today 24h volume is $5bil on derivatives vs $200mil on spot).

Can you revert commit? Or create two different options so users can choose what they need: Bybit-spot (current) or Bybit-derivatives (old).

Thanks,
troky

**Comment by aneonex** [comment]
I added "Bybit (Derivatives)" as a different option.
This will be included in the next app release v2.64.

**Comment by troky** [comment]
That's great! :)
Thanks.

**Comment by aabiryukov** [comment]
Updated app is available in Google Play
