### ISSUE TITLE
Request to add new exchanges - Exbitron, Txbit, as well as an error when loading SafeTrade exchange data.

### ISSUE THREAD

**Issue by Shah-man** [aneonex/BitcoinChecker#228]
Hello, thank you so much for your hard work! This is the best cryptocurrency price tracking app!

I ask you to add exchanges: Exbitron - https://www.exbitron.com / and also Txbit - https://www.txbit.io / there are interesting coins on these exchanges that need to be tracked.

SafeTrade - when trying to load the list message: Last sync: never "Error: Authentication required (403)"

Thank you! Be healthy and happy!
![SafeTrade](https://user-images.githubusercontent.com/123202349/213792599-e07c75b0-33e8-495e-b59e-f58d775b4506.jpg)

**Comment by aneonex** [comment]
1) Regarding SafeTrade
- Please try again, maybe it is a temporary issue on the exchange side. I can't reproduce this.
- If you still have this issue, try to open directly SafeTrade API url from the browser on your device: https://safe.trade/api/v2/peatio/public/markets
This may show the details of the issue (maybe network/proxy issue, maybe this exchange inaccessible from your IP region).

2) Exbitron, Txbit
I will analyze the API of these exchanges and then add it to the app.

Thank you for the feedback.

**Comment by aneonex** [comment]
Exbitron and Txbit added in the app v2.64
