### ISSUE TITLE
Multiple bug reports for Xiaomi device

### ISSUE THREAD

**Issue by JC-S** [aneonex/BitcoinChecker#229]
Device: Xiaomi Mi 12 S
Software version: MIUI 14.0.5 (Android 13)

Bug 1:
App fails to stay in background, even with battery saving set to unlimited.

Bug 2:
Can't change global update interval. Every time you change it, go back to previous page and come back, it goes back to 10 minutes.

**Comment by aneonex** [comment]
Please update to the latest app v2.64.1 (already available in Google Play).

Bug 1: If the problem persists after the update, please describe the symptoms in more detail (how often, what do you mean by "fails", how many active price checkers in the app, ...)

Bug 2: fixed in v2.64.1

**Comment by JC-S** [comment]
Both issues are fixed in the update. Bro how can you be so amazing??
