### ISSUE TITLE
sleep mode

### ISSUE THREAD

**Issue by qwert76ya** [aneonex/BitcoinChecker#27]
does not work in sleep mode
It would be nice if this worked

**Comment by aneonex** [comment]
Describe your device please. Model and version of android.

**Comment by qwert76ya** [comment]
HUAWEI P smart 2019 https://consumer.huawei.com/ru/phones/p-smart-2019/specs/
phone has been updated to version 10 android

**Comment by qwert76ya** [comment]
![Screenshot_20201111_013402_com huawei systemmanager](https://user-images.githubusercontent.com/52155840/98741673-1f405400-23be-11eb-9cd6-3d0c63a589f7.jpg)

**Comment by qwert76ya** [comment]
![98741673-1f405400-23be-11eb-9cd6-3d0c63a589f7](https://user-images.githubusercontent.com/52155840/98742531-a93cec80-23bf-11eb-8890-77115789d443.jpg)

**Comment by aneonex** [comment]
Thank you for details.
Try to turn off the option "Автоматическое управление" ("Manage automatically") for Bitcoin Checker app. This option can block  runs checker in sleep mode.

**Comment by qwert76ya** [comment]
Thank you very much.
I figured it out
It was about setting up the phone but elsewhere
this fucking huawei with its settings

**Comment by aneonex** [comment]
Now you can turn off sleep mode for the app more easy. Check the app settings in the latest version (v2.16).
