### ISSUE TITLE
Minimized notifications no longer grouped?

### ISSUE THREAD

**Issue by tonypirasteh** [aneonex/BitcoinChecker#35]
Thanks for keeping this updated! It might be an issue on my end, but I checked that all the app settings were the same and that notification settings within Android 11 were the same, but I'm getting different behavior.

I just installed and noticed that the collapsed/minimized notifications don't group together under one "bitcoin checker" notification as the previously maintained version's notifications did. I've attached screenshots below, thanks for looking into this and if I'm missing something please give me a heads up.

Attached old vs new behavior.
![Screenshot_20201105-082952~3](https://user-images.githubusercontent.com/69864261/100481491-12537e00-30a9-11eb-8b97-516d958d05fb.png)
![Screenshot_20201127-120523~2](https://user-images.githubusercontent.com/69864261/100481692-c6ed9f80-30a9-11eb-8339-264ebf239499.png)

**Comment by aneonex** [comment]
Autogrouping appeared in recent versions of Android. Grouped notifications require an extra click to see the currency price, which is inconvenient for frequent use. For this reason, notifications are displayed separately.

I will consider making this behavior optional.

**Comment by tonypirasteh** [comment]
Thank you for the quick reply, and thank you for the consideration!

**Comment by 29988122** [comment]
Just want to pass by and say thank you

The current behavior (unwanted behavior for tonypirasteh) is exactly what I need, but not able to, in the original fork of the unmaintained version.

Thank you for keep maintaining the codebase!

**Comment by aneonex** [comment]
@29988122 Thanks for your opinion.

Regarding the notifications order. 
At first glance, this is possible. But for order I see to reuse order of the checkers in the app main window (you can reorder them by Drag&Drop or by sort type).
Create a separate issue, please. I will try to implement this in the future.

**Comment by aneonex** [comment]
Grouped notifications now available (the latest app version 2.28). 
To enable grouping, go to settings: Customize notifications->Group notifications.
