### ISSUE TITLE
Denominate volume in quote currency instead of base?

### ISSUE THREAD

**Issue by leocape** [aneonex/BitcoinChecker#48]
For exchange integrations, is it possible to have the volume (VOL) in the UI be denominated in the quote currency instead of the base currency?

Currently for a BTC/USD pair it defaults to the base currency eg BTC, but it would be nice to have the option to have it be in the quote currency eg USD

Current:
VOL: 500 BTC

To be:
VOL: 8m USD

(I mean specify it during an integration - not as a new feature in the ui - although that would be a cool feature too )

**Comment by aneonex** [comment]
Exchanges rarely provide info about the quote currency volume. It can be calculated through avg price (base_vol*avg_price), but avg price also not always available. 

And one more aspect regarding option. 
The more options, the more difficult it is to use the app. Therefore, I do't want to add option to the settings.

I suppose the possible solution:
Display qoute currency volume by right side of base volume and only when this data (quote vol or avg price) provided by exchange.

Current:
Vol: 500 BTC

To be:
Vol: 500 BTC | 9 500 000 USD

What you think about this?

**Comment by aneonex** [comment]
Added quote volume, when the exchange provides it.
How it looks:
![image](https://user-images.githubusercontent.com/69394046/148228358-6a82f092-121f-4cfd-ba80-e28418396509.png)

Will be available in the next app release v2.51.
