### ISSUE TITLE
Checkers using Bitso are not working

### ISSUE THREAD

**Issue by reuhtte** [aneonex/BitcoinChecker#49]
Every checker using Bitso as exchange are not working and are showing "Parsing error" message.

**Comment by aneonex** [comment]
Needed more info:
1) What version of app you are using? (latest is v2.19)
2) Check the url from your browser on device: "https://api.bitso.com/v3/ticker?book=btc_usd". Is it accessable and what content you are recieve?
3) What is model of your device and version of android?

**Comment by llildur** [comment]
It´s working now
