### ISSUE TITLE
Add BitMax

### ISSUE THREAD

**Issue by daanutrecht1980** [aneonex/BitcoinChecker#53]
Please add BitMax (bitmax.io) to the list

**Comment by aneonex** [comment]
The exchange is added. 
Will be included to the next app version (v2.20).

**Comment by daanutrecht1980** [comment]
Hi,

Very nice - thanks! 😄 😄

Kind regards,

Daan.

________________________________
Van: Aneonex Software <notifications@github.com>
Verzonden: zaterdag 26 december 2020 09:10
Aan: aneonex/BitcoinChecker <BitcoinChecker@noreply.github.com>
CC: daanutrecht1980 <daanutrecht1980@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [aneonex/BitcoinChecker] Add BitMax (#53)


The exchange is added.
Will be included to the next app version (v2.20).
