### ISSUE TITLE
Binance network error.

### ISSUE THREAD

**Issue by Mir0slavKrstiC** [aneonex/BitcoinChecker#56]
I can't receive the pairs from Binance. I get a network error.

![1609158145108](https://user-images.githubusercontent.com/58627516/103214300-5c31bd00-4910-11eb-829c-ed5e795d96ef.jpg)

**Comment by aneonex** [comment]
The app directly working with exchanges API. Issue looks like Binance API is not accessable from your network, or temporary problems with the access.
Try to open next url in the browser on your phone: https://api.binance.com/api/v3/exchangeInfo
If url does not open, check your network.
If url opens, try to resync pairs in app.
