### ISSUE TITLE
Alarming at incorrect values

### ISSUE THREAD

**Issue by mirzataha** [aneonex/BitcoinChecker#57]
When I set alarm for bitcoin/usd on +- 1000$ it never alarm on 1000 value changes, it keeps alarming at 5 or 10 or 20 dollar changes in value .. plz help

**Comment by aneonex** [comment]
Can you provide screenshot of your alert?
Also needed info about your device (model, android version).

**Comment by aneonex** [comment]
No response for a long time. Reactivate the issue if the problem still exists.
