### ISSUE TITLE
New crypto exchange recommendation

### ISSUE THREAD

**Issue by Treyuk** [aneonex/BitcoinChecker#63]
Hi, I appreciate the hard work and all the alert features this app offers. The only issue im having is finding some of the newer coins only available on Hotbit which is the exchange I would like to see added. Thank you for all your hardwork. This app stands out from the rest by far.

**Comment by aneonex** [comment]
Hotbit exchange added and will be included to the next app version (v2.23).
Thanks for your feedback.
