### ISSUE TITLE
Widget freeze

### ISSUE THREAD

**Issue by Deedjee** [aneonex/BitcoinChecker#65]
At  some point the widget does not refresh anymore. I have to remove it and recreate it on the phone. 
The application However still works. 
My phone: xiaomi MI 9T pro.

**Comment by aneonex** [comment]
Some questions:
1) Are you using latest app version v2.22 ?
1) How many checkers in your list?
1) What does the windget look like when it stops updating? Are there any messages?
1) When the widget stops updating, try adding a new checker to list. Does the new checker appear in the widget?

**Comment by aneonex** [comment]
Out of date
