### ISSUE TITLE
Vibrate doesn't work

### ISSUE THREAD

**Issue by tungns1210** [aneonex/BitcoinChecker#67]
I set an alarm with vibrage on and its doesn't work
![Screenshot_20210119-091214](https://user-images.githubusercontent.com/77651347/104979318-95081200-5a36-11eb-8437-b0aceb79c77f.jpg)
![Screenshot_20210119-091226](https://user-images.githubusercontent.com/77651347/104979426-d4366300-5a36-11eb-8676-45b02e7aedc0.jpg)

**Comment by aneonex** [comment]
Fixed in the latest app v2.24.
