### ISSUE TITLE
Binance Future Coin-M

### ISSUE THREAD

**Issue by godtrix** [aneonex/BitcoinChecker#69]
Hi, it's so wonderful that you've added binance future! 👍 but my slight problem is that I'm trading on the Coin-M "BTCUSD perpetual", which is not yet available on your app, hopefully some day will add them 🙏 thank you very much

**Comment by aneonex** [comment]
COIN-M perpetual futures are now availale in Binance Futures. Added in the latest app version 2.38.2.
