### ISSUE TITLE
Two little suggestions - Feature request

### ISSUE THREAD

**Issue by Wolftech-Chile** [aneonex/BitcoinChecker#73]
Hello, bitcoin ckecker is really a perfect tool, only two suggestions I have that hopefully can be implemented.
1 ° Add Chilean exchange such as Orionx.com, Buda.com and Cryptomkt.com in that order of preference
2 ° Set font size in widget

Thank you very much, I hope you can add the Chilean exchange Orionx.com, that's where I have my crypto and i lost opportunities because the Orionx.com web is pretty limited.
Best Regards
Mr. Roboto from Chile

**Comment by aneonex** [comment]
1) All exchanges was added and will be included in the next app release v2.25 (planned within a week).
2) Regarding font size. Create a separate issue, please, and describe your problem in more detail (maybe with screenshots).
