### ISSUE TITLE
Font size in widget

### ISSUE THREAD

**Issue by Wolftech-Chile** [aneonex/BitcoinChecker#77]
Thanks again!!
I mean being able to choose the font size in the widget settings.
In the upload image see the widget in action
Thank you very much.
Can i donate by paypal?
Best regards
Gustavo Aka Mr. Roboto
from Chile

![Screenshot_20210214-164534](https://user-images.githubusercontent.com/49559114/107887344-396d5f00-6ee4-11eb-83c2-9def023e6bce.png)
![Screenshot_20210214-164555](https://user-images.githubusercontent.com/49559114/107887345-3e321300-6ee4-11eb-805b-e73d6333b4ac.png)

**Comment by aneonex** [comment]
In the next app version, I plan to optimize price size - do not display decimal points in prices greater than 10000. In your case: 35.136.703,31 CLP -> 35.136.703 CLP.
This should reduce your problem.

Plus, there are additional solutions:
1) Turn off "Compact mode" in widget to optimize horizontal space.
2) Stretch horizontally in place of the icons on the left or right.

Summary.
I don't see the need to complicate the widget by adding a new setting.

> Can i donate by paypal?

No. You can donate BTC or ETH: https://github.com/aneonex/BitcoinChecker#donate-to-project-development
But this will not affect the final decision.
Thank you.

**Comment by aneonex** [comment]
Price length optimized in the latest app version v2.26.
