### ISSUE TITLE
Can't set an alarm for low priced altcoins

### ISSUE THREAD

**Issue by Donk1234** [aneonex/BitcoinChecker#85]
Example:

Hitbtc
If you try to set a alarm for KIN coin at a price of 0.00000000172, Bitcoin Checker will register a value of 0. It does not accept a value lower than the 8th decimal. A lower value will be rounded up.

Is it possible to increase the decimals like the old version of Bitcoin Checker?

Greetings, 

Don

**Comment by aneonex** [comment]
Fix will be included in the next app release v2.26 (in about a week).
