### ISSUE TITLE
Feature request: Turn off/on all checkers

### ISSUE THREAD

**Issue by sethxp** [aneonex/BitcoinChecker#93]
Hi, is it possible to add "slider" to turn off/on all checkers at once?

Thanks
Seth

**Comment by Kerbox2000** [comment]
I have tons of alarms and turning everything off and on one by one is tedious. This would be a great new features

**Comment by aneonex** [comment]
This feature will be included in the next release. Below is a screenshot of how it will look.
If you have any comments, let me know.

![image](https://user-images.githubusercontent.com/69394046/122364346-5a14f680-cf62-11eb-9c34-04f5eb1f9bd0.png)

**Comment by Kerbox2000** [comment]
Looks great, good job man!

**Comment by sethxp** [comment]
Great, is it possible to add 2 functions? Disable/enable all checkers and disable/enable active checkers.  Thanks.

**Comment by aneonex** [comment]
@sethxp Every checker has only one state - enabled (on) or disabled (off). What do you mean by enabling active checkers?

**Comment by sethxp** [comment]
I mean i have for example 15 checkers, 10 enabled 5 disabled. At night i want to click Disable active checkers. And in morging click on activate/enable last state before disabling - 10 on 5 off.Dne 18. 6. 2021 15:58 napsal uživatel Aneonex Software ***@***.***>:
@sethxp Every checker has only one state - enabled (on) or disabled (off). What do you mean by enabling active checkers?

**Comment by aneonex** [comment]
@sethxp Do you turn off checkers at night because of the sound of the alerts? 
If you turn off the checkers completely, then you will not see the latest price alerts in the morning in the notification bar. 
Perhaps you need something like a quiet mode?

@Kerbox2000 Please describe your case, for what purpose you turning off all checkers or alerts?

**Comment by sethxp** [comment]
Yes, i need some kind of quiet mode at night because price notifications are also sended repeatly to my smart watch untill dismiss. So one slider to turn off/on notifications?Dne 19. 6. 2021 19:27 napsal uživatel Aneonex Software ***@***.***>:
@sethxp Do you turn off checkers at night because of the sound of the alerts?
If you turn off the checkers completely, then you will not see the latest price alerts in the morning in the notification bar.
Perhaps you need something like a quiet mode?
@Kerbox2000 Please describe your case, for what purpose you turning off all checkers or alerts?

**Comment by Kerbox2000** [comment]
I turn off my alerts so I can sleep at night, I am not a day trader but still curious about price movements.

**Comment by Kerbox2000** [comment]
Any news on this? I would be just fine with on and off function for all alerts for now.

**Comment by aneonex** [comment]
I can't find simple and clear solution yet. I see one of the following options:
1) "Silent mode" - turns off all sounds, including speech and vibration. Price updates and alerts still work silently in the notification bar. 
Disadvantages: This does not solve the issue with smartwatch notifications.
2) "Quiet mode" - same as "Silent mode" but alerts also does not work, only the price is updated silently. 
Disadvantages: It makes unreliable the alerts and price checkpoints updates. Also not sure if this will solve the smartwatch issue.
3) "Stop mode" - stop all price updates. Likewise, when all checkers are disabled. Simply to use.
Disadvantages: No price updates, no alerts, no any notifications in the top bar.

Option 3 seems to me the simplest and most clear. This is most close to the original issue.

One more note.
Android has standard "Do Not Disturb" mode (with night schedule and app filters), which does not require additional application settings to disable notifications. Have you tried using this?

**Comment by sethxp** [comment]
Ok, number 3 Stop mode. I like that. It's kind of suprise every morning if prices are up or down from latest "stop".Dne 16. 8. 2021 16:01 napsal uživatel Aneonex Software ***@***.***>:
I can't find simple and clear solution yet. I see one of the following options:
"Silent mode" - turns off all sounds, including speech and vibration. Price updates and alerts still work silently in the notification bar.
Disadvantages: This does not solve the issue with smartwatch notifications."Quiet mode" - same as "Silent mode" but alerts also does not work, only the price is updated silently.
Disadvantages: It makes unreliable the alerts and price checkpoints updates. Also not sure if this will solve the smartwatch issue."Stop mode" - stop all price updates. Likewise, when all checkers are disabled. Simply to use.
Disadvantages: No price updates, no alerts, no any notifications in the top bar.
Option 3 seems to me the simplest and most clear. This is most close to the original issue.
One more note.
Android has standard "Do Not Disturb" mode (with night schedule and app filters), which does not require additional application settings to disable notifications. Have you tried using this?

**Comment by aneonex** [comment]
Design preview:

![image](https://user-images.githubusercontent.com/69394046/129603826-bbb8f497-f30f-4360-a22a-8d5fbee4155b.png)

"Stop mode" is renamed in a more intuitive "Pause".

**Comment by Kerbox2000** [comment]
Again, this looks good, hope this will make it to the next release :-)

**Comment by sethxp** [comment]
Ok, perfect, thanks.Dne 16. 8. 2021 20:41 napsal uživatel Kerbox2000 ***@***.***>:
Again, this looks good, hope this will make it to the next release :-)

**Comment by aneonex** [comment]
This feature implemented and included to the new release 2.45. Will be available during this week.
