### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by terrorist96** [aneonex/BitcoinChecker#94]
![SmartSelect_20210323-184200_Bitcoin Checker](https://user-images.githubusercontent.com/12802056/112228292-7a554380-8c07-11eb-9f5f-20bd6b397f10.jpg)

**Comment by aneonex** [comment]
Trading with CRV not yet available on Coinbase: https://pro.coinbase.com/trade/CRV-USD
I added more clear error. Will be included in the next app v2.29.
