### ISSUE TITLE
Add Crypto.com to exchanges?

### ISSUE THREAD

**Issue by nnikor** [aneonex/BitcoinChecker#98]
Hi! I think that's one of the major exchanges so it should be added if possible. Thanks! :)

**Comment by aneonex** [comment]
Added to sources and will be included to next app v2.29.

**Comment by nnikor** [comment]
Ooh nice! That was quick, much appreciated! :) Will give you a five star
review in google play after that update.

Best regards, Niko Rantala

**Comment by aneonex** [comment]
Ok, thanks :)
